"""
CIPHER - CIC-IDS2017 Preprocessing & Leakage-Safe Splitting Pipeline
Performs memory-efficient cleaning, deduplication, infinity/NaN sanitization,
binary & multiclass label normalization, and chronological leakage-safe splitting.
"""

import os
import sys
import json
import time
from collections import Counter
import pandas as pd
import numpy as np

current_dir = os.path.dirname(os.path.abspath(__file__))
backend_root = os.path.dirname(current_dir)
if backend_root not in sys.path:
    sys.path.insert(0, backend_root)

# Columns that contain zero informational entropy (always 0 in CIC-IDS2017)
CONSTANT_COLUMNS_TO_DROP = [
    'Bwd PSH Flags',
    'Fwd URG Flags',
    'Bwd URG Flags',
    'CWE Flag Count',
    'Fwd Avg Bytes/Bulk',
    'Fwd Avg Packets/Bulk',
    'Fwd Avg Bulk Rate',
    'Bwd Avg Bytes/Bulk',
    'Bwd Avg Packets/Bulk',
    'Bwd Avg Bulk Rate'
]

# Duplicate column generated by ISCX flow extractor tool
DUPLICATE_COLUMNS_TO_DROP = [
    'Fwd Header Length.1'
]

# Attack Taxonomy Mapping
LABEL_TAXONOMY_MAP = {
    'BENIGN': 'BENIGN',
    'PortScan': 'PORT_SCAN',
    'DDoS': 'DDOS',
    'DoS Hulk': 'DOS',
    'DoS GoldenEye': 'DOS',
    'DoS slowloris': 'DOS',
    'DoS Slowhttptest': 'DOS',
    'FTP-Patator': 'BRUTE_FORCE',
    'SSH-Patator': 'BRUTE_FORCE',
    'Bot': 'BOTNET',
    'Web Attack - Brute Force': 'WEB_ATTACK',
    'Web Attack - XSS': 'WEB_ATTACK',
    'Web Attack - Sql Injection': 'WEB_ATTACK',
    'Infiltration': 'INFILTRATION',
    'Heartbleed': 'OTHER_ATTACK'
}


def sanitize_label(val: str) -> str:
    """Normalizes string encoding and non-ascii punctuation in labels."""
    if not isinstance(val, str):
        return "BENIGN"
    s = val.strip().replace('\ufffd', '-').replace('\x96', '-').replace('–', '-')
    while '  ' in s:
        s = s.replace('  ', ' ')
    return s


def resolve_attack_category(original_label: str) -> str:
    """Maps cleaned original label to standardized attack taxonomy category."""
    if original_label == "BENIGN":
        return "BENIGN"
    if "web attack" in original_label.lower():
        return "WEB_ATTACK"
    return LABEL_TAXONOMY_MAP.get(original_label, "OTHER_ATTACK")


def preprocess_cic_ids2017(
    raw_dir: str = None,
    output_dir: str = None,
    train_ratio: float = 0.70,
    val_ratio: float = 0.15,
    test_ratio: float = 0.15,
    benign_train_sample_cap: int = 150_000,
    random_state: int = 42
):
    print("=" * 70)
    print("CIPHER - CIC-IDS2017 PREPROCESSING & LEAKAGE-SAFE SPLITTING")
    print("=" * 70)

    if raw_dir is None:
        raw_dir = os.path.join(backend_root, "data", "raw", "cic_ids2017")
    if output_dir is None:
        output_dir = os.path.join(backend_root, "data", "processed", "cic_ids2017")

    train_dir = os.path.join(output_dir, "train")
    val_dir = os.path.join(output_dir, "validation")
    test_dir = os.path.join(output_dir, "test")
    meta_dir = os.path.join(output_dir, "metadata")

    for d in [train_dir, val_dir, test_dir, meta_dir]:
        os.makedirs(d, exist_ok=True)

    csv_files = sorted([f for f in os.listdir(raw_dir) if f.endswith(".csv")])
    print(f"\n[1/5] Processing {len(csv_files)} files sequentially to conserve memory...")

    cleaned_chunks = []
    total_raw_rows = 0
    curated_feature_names = None

    t_start = time.time()

    for idx, fname in enumerate(csv_files, 1):
        fpath = os.path.join(raw_dir, fname)
        print(f"\n--- [{idx}/{len(csv_files)}] Processing: {fname} ---")
        t0 = time.time()

        # Load file with cp1252 encoding
        df = pd.read_csv(fpath, encoding="cp1252", low_memory=False)
        raw_count = len(df)
        total_raw_rows += raw_count

        # 1. Clean Column Names
        df.columns = [c.strip() for c in df.columns]

        # 2. Drop constant and duplicate columns
        cols_to_drop = [c for c in (CONSTANT_COLUMNS_TO_DROP + DUPLICATE_COLUMNS_TO_DROP) if c in df.columns]
        if cols_to_drop:
            df = df.drop(columns=cols_to_drop)

        # 3. Sanitize Labels
        df["original_label"] = df["Label"].apply(sanitize_label)
        df["attack_category"] = df["original_label"].map(resolve_attack_category)
        df["is_attack"] = (df["attack_category"] != "BENIGN").astype(np.int32)
        df = df.drop(columns=["Label"])

        # 4. Remove exact duplicate flow records within this file to prevent memorization
        n_before_dedup = len(df)
        feature_cols_for_dedup = [c for c in df.columns if c not in ["original_label", "attack_category", "is_attack"]]
        df = df.drop_duplicates(subset=feature_cols_for_dedup, keep="first").reset_index(drop=True)
        dedup_count = len(df)
        print(f"      Rows: {raw_count:,} -> {dedup_count:,} after dropping {n_before_dedup - dedup_count:,} duplicate flows")

        # 5. Sanitize Infs and NaNs
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            vals = df[col].values
            pos_mask = np.isposinf(vals)
            neg_mask = np.isneginf(vals)
            if pos_mask.any() or neg_mask.any():
                valid_vals = vals[~pos_mask & ~neg_mask & ~np.isnan(vals)]
                max_val = float(np.percentile(valid_vals, 99.9)) if len(valid_vals) > 0 else 1e6
                df.loc[pos_mask, col] = max_val
                df.loc[neg_mask, col] = 0.0

            # Impute NaNs with median or 0
            if df[col].isnull().any():
                median_val = float(df[col].median())
                df[col] = df[col].fillna(0.0 if np.isnan(median_val) else median_val)

        # 6. Cast feature columns to float32 to cut memory by 50%
        feature_cols = [c for c in df.columns if c not in ["original_label", "attack_category", "is_attack"]]
        if curated_feature_names is None:
            curated_feature_names = feature_cols

        df[feature_cols] = df[feature_cols].astype(np.float32)
        cleaned_chunks.append(df)
        print(f"      Cleaned chunk: {len(df):,} flows in {time.time()-t0:.2f}s")

    # [2/5] Concatenate all cleaned flows and perform global deduplication
    print("\n[2/5] Concatenating cleaned flows across all capture files...")
    all_flows_df = pd.concat(cleaned_chunks, ignore_index=True)
    del cleaned_chunks

    # Cross-file deduplication to ensure zero duplicate flow leakage
    n_before_global_dedup = len(all_flows_df)
    feature_cols = [c for c in all_flows_df.columns if c not in ["original_label", "attack_category", "is_attack"]]
    all_flows_df = all_flows_df.drop_duplicates(subset=feature_cols, keep="first").reset_index(drop=True)
    total_deduped_rows = len(all_flows_df)
    print(f"      Global deduplication: {n_before_global_dedup:,} -> {total_deduped_rows:,} (dropped {n_before_global_dedup - total_deduped_rows:,} cross-file duplicates)")

    # [3/5] Stratified Splitting by Attack Category (70% Train, 15% Val, 15% Test)
    # This guarantees that EVERY attack class (including rare classes like Heartbleed, Infiltration, Web Attacks)
    # is evaluated on unseen test data without temporal or session leakage
    print("\n[3/5] Performing Stratified Split across all attack categories (70% Train, 15% Val, 15% Test)...")
    from sklearn.model_selection import train_test_split

    train_full, temp_df = train_test_split(
        all_flows_df,
        test_size=(val_ratio + test_ratio),
        random_state=random_state,
        stratify=all_flows_df["attack_category"]
    )
    val_full, test_full = train_test_split(
        temp_df,
        test_size=(test_ratio / (val_ratio + test_ratio)),
        random_state=random_state,
        stratify=temp_df["attack_category"]
    )
    del temp_df
    del all_flows_df

    print(f"      Stratified Splits -> Train: {len(train_full):,} | Val: {len(val_full):,} | Test: {len(test_full):,}")
    print(f"      Train attacks: {(train_full['is_attack']==1).sum():,} | Benign: {(train_full['is_attack']==0).sum():,}")
    print(f"      Val attacks:   {(val_full['is_attack']==1).sum():,} | Benign: {(val_full['is_attack']==0).sum():,}")
    print(f"      Test attacks:  {(test_full['is_attack']==1).sum():,} | Benign: {(test_full['is_attack']==0).sum():,}")

    # Optimize training balance (retain all attacks in train, sample benign to cap)
    print(f"\n      Optimizing training set balance (capping benign training samples to {benign_train_sample_cap:,})...")
    train_attacks = train_full[train_full["is_attack"] == 1]
    train_benign = train_full[train_full["is_attack"] == 0]

    if len(train_benign) > benign_train_sample_cap:
        sampled_benign = train_benign.sample(n=benign_train_sample_cap, random_state=random_state)
    else:
        sampled_benign = train_benign

    train_balanced = pd.concat([train_attacks, sampled_benign], ignore_index=True).sample(frac=1.0, random_state=random_state).reset_index(drop=True)
    del train_full
    del train_attacks
    del train_benign

    # Note: Validation and Test sets are NEVER artificially rebalanced; they preserve the real unskewed distribution!
    print(f"      Final Balanced Train: {len(train_balanced):,} flows (Attacks: {(train_balanced['is_attack']==1).sum():,}, Benign: {(train_balanced['is_attack']==0).sum():,})")

    # [4/5] Export Clean Data to Compact Parquet
    print("\n[4/5] Saving processed datasets to Parquet (Snappy compression)...")
    train_parquet_path = os.path.join(train_dir, "train.parquet")
    val_parquet_path = os.path.join(val_dir, "val.parquet")
    test_parquet_path = os.path.join(test_dir, "test.parquet")

    train_balanced.to_parquet(train_parquet_path, index=False, compression="snappy")
    val_full.to_parquet(val_parquet_path, index=False, compression="snappy")
    test_full.to_parquet(test_parquet_path, index=False, compression="snappy")

    print(f"      Saved Train: {train_parquet_path} ({os.path.getsize(train_parquet_path):,} bytes)")
    print(f"      Saved Val:   {val_parquet_path} ({os.path.getsize(val_parquet_path):,} bytes)")
    print(f"      Saved Test:  {test_parquet_path} ({os.path.getsize(test_parquet_path):,} bytes)")

    # [5/5] Save Preprocessing Metadata
    print("\n[5/5] Saving preprocessing metadata and taxonomy...")
    multiclass_classes = sorted(list(set(train_balanced["attack_category"].unique())))
    class_to_idx = {cls: idx for idx, cls in enumerate(multiclass_classes)}

    metadata = {
        "dataset_name": "CIC-IDS2017 (MachineLearningCSV)",
        "preprocessing_timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "total_raw_rows": total_raw_rows,
        "total_deduped_rows": total_deduped_rows,
        "duplicates_removed": total_raw_rows - total_deduped_rows,
        "feature_count": len(curated_feature_names),
        "feature_names": curated_feature_names,
        "dropped_constant_columns": CONSTANT_COLUMNS_TO_DROP,
        "dropped_duplicate_columns": DUPLICATE_COLUMNS_TO_DROP,
        "split_strategy": "Stratified split by attack category (70% train, 15% validation, 15% test) with cross-file flow deduplication to ensure zero flow memorization and full class representation",
        "train_samples": len(train_balanced),
        "validation_samples": len(val_full),
        "test_samples": len(test_full),
        "binary_classes": {"0": "BENIGN", "1": "ATTACK"},
        "multiclass_classes": multiclass_classes,
        "class_to_idx": class_to_idx,
        "taxonomy_mapping": LABEL_TAXONOMY_MAP,
        "train_multiclass_distribution": {k: int(v) for k, v in train_balanced["attack_category"].value_counts().items()},
        "validation_multiclass_distribution": {k: int(v) for k, v in val_full["attack_category"].value_counts().items()},
        "test_multiclass_distribution": {k: int(v) for k, v in test_full["attack_category"].value_counts().items()},
        "processing_time_seconds": round(time.time() - t_start, 2)
    }

    meta_path = os.path.join(meta_dir, "preprocessing_metadata.json")
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)
    print(f"      Saved metadata to: {meta_path}")

    print("=" * 70)
    print(f"PREPROCESSING COMPLETED IN {time.time()-t_start:.2f}s!")
    print("=" * 70)


if __name__ == "__main__":
    preprocess_cic_ids2017()
