"""
CIPHER Phishing API Request and Response Schemas
Strongly typed Pydantic models for REST endpoints.
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator


class PhishingAnalyzeRequest(BaseModel):
    """Input payload for phishing URL inspection."""
    url: str = Field(
        ...,
        description="The URL to inspect for phishing indicators.",
        examples=["https://example.com/login", "http://paypal-verification.xyz/auth"]
    )
    page_features: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional webpage/DOM features provided by browser extension (extensible)."
    )
    source: Optional[str] = Field(
        default="api",
        description="Source identifier (e.g. 'api', 'browser_extension', 'cli')."
    )

    @field_validator("url")
    @classmethod
    def validate_url_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("URL cannot be empty or whitespace.")
        v_clean = v.strip()
        if len(v_clean) > 4096:
            raise ValueError("URL exceeds maximum length of 4096 characters.")
        return v_clean


class PhishingAnalyzeResponse(BaseModel):
    """Output payload representing CIPHER's complete security verdict."""
    classification: str = Field(
        ...,
        description="Categorical threat assessment: 'LEGITIMATE', 'SUSPICIOUS', or 'LIKELY_PHISHING'.",
        examples=["LIKELY_PHISHING"]
    )
    risk_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="CIPHER's unified cybersecurity threat risk score (0-100).",
        examples=[87]
    )
    severity: str = Field(
        ...,
        description="Severity level: 'LOW', 'MEDIUM', 'HIGH', or 'CRITICAL'.",
        examples=["CRITICAL"]
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Classifier certainty in the ML prediction (0.0 - 1.0).",
        examples=[0.94]
    )
    ml_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Raw machine learning phishing probability score (0.0 - 1.0).",
        examples=[0.91]
    )
    heuristic_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Score generated by the independent heuristic rule engine (0 - 100).",
        examples=[78]
    )
    reasons: List[str] = Field(
        ...,
        description="Human-readable explanations detailing detected anomalies and risk indicators.",
        examples=[
            "Suspicious URL structure with credential tokens",
            "Elevated domain lexical randomness indicative of DGA generation"
        ]
    )
    recommendation: str = Field(
        ...,
        description="Actionable user guidance.",
        examples=["Do not enter credentials on this page."]
    )
    model_version: str = Field(
        ...,
        description="Version string of the active machine learning model.",
        examples=["phiusiil-rf-v1"]
    )
    event_id: Optional[str] = Field(
        default=None,
        description="Local tracking ID for the recorded privacy-safe security event."
    )
